version: "3.9"
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}
    image: erasme/maquette_augmentee_frontend:latest
    container_name: maquette_augmentee_frontend
    ports:
      - "8000:80"
    

      